# Generated by Django 5.0.6 on 2024-07-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='juegosComprar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('plataforma', models.CharField(max_length=255)),
                ('precio', models.IntegerField(max_length=6)),
                ('multijugador', models.BooleanField(default=False)),
                ('solitario', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='juegosTerminados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('plataforma', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=255)),
                ('recomiendo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='plataformas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePlataforma', models.CharField(max_length=255)),
                ('membresia', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('plataforma', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=255)),
                ('multijugador', models.BooleanField(default=False)),
                ('solitario', models.BooleanField(default=False)),
            ],
        ),
    ]
