# Generated by Django 5.0.6 on 2024-07-14 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_juegoscomprar_precio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='juegoscomprar',
            options={'ordering': ['nombre'], 'verbose_name': 'juego comprar', 'verbose_name_plural': 'juegos comprar'},
        ),
        migrations.AlterModelOptions(
            name='juegosterminados',
            options={'ordering': ['nombre'], 'verbose_name': 'juego terminado', 'verbose_name_plural': 'juegos terminados'},
        ),
        migrations.AlterModelOptions(
            name='plataformas',
            options={'ordering': ['nombrePlataforma'], 'verbose_name': 'plataforma', 'verbose_name_plural': 'plataformas'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['nombre'], 'verbose_name': 'wishlist', 'verbose_name_plural': 'wishlist'},
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='avatares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
